update readme

diff --git a/core/Makefile b/core/Makefile
--- a/core/Makefile
+++ b/core/Makefile
@@ -30,10 +30,14 @@ unit-tests:
 publish-domain-http:
 	@VERSION=`grep '^version =' domain-http/Cargo.toml | head -n 1 | sed -E 's/version = "(.*)"/\1/'`; \
 	echo "posemesh-domain-http version: $$VERSION, will be published to npm and cargo"; \
-	IS_STABLE=`echo "$$VERSION" | grep -E '.*-rc|.*-beta|.*-alpha'` ; \
-	if [ -z "$$IS_STABLE" ]; then \
-		if ! grep -q "## v$${VERSION}" domain-http/README.md; then \
-			echo "ERROR: No changelog for v$${VERSION} found in domain-http/README.md"; \
+	IS_UNSTABLE=`echo "$$VERSION" | grep -E '.*-rc|.*-beta|.*-alpha'` ; \
+	if [ -z "$$IS_UNSTABLE" ]; then \
+		if ! grep -q "## v$${VERSION}" domain-http/CHANGELOG.md; then \
+			echo "ERROR: No changelog for v$${VERSION} found in domain-http/CHANGELOG.md"; \
+			exit 1; \
+		fi; \
+		if [ -z "$$CI" ]; then \
+			echo "Stable releases should only be published by CI. Aborting."; \
 			exit 1; \
 		fi; \
 	fi; \
@@ -55,7 +59,7 @@ publish-domain-http:
 	fi
 	@cargo publish -p posemesh-domain-http
 	@cd domain-http/pkg && \
-	if [ -z "$$IS_STABLE" ]; then \
+	if [ -z "$$IS_UNSTABLE" ]; then \
 		npm publish --tag "v$$VERSION"; \
 	else \
 		npm publish; \
