feat: add Linux with AMD64 and ARM64 build (#49)
* chore: add linux base

* chore: install GCC cross-cc for ARM64

* chore: add OpenCV build

* chore: try to fix

* fix: attempt2

* chore: try to fix linker

* fix attempt 3

* test2

* testttt

* test revert

* attempt

* attempt4

* attempt

* att

* fix

* clean

* chore: add uname check

* attempt fix opencv build

* attempt

* crosscc

* add cpu baseline detect ?

* try to enable neon

* document that API gentool needs to be executed

* try installing g++

* ls

* static lib

* attempt to build linux

* fix

* add linux to API.h check

* fix

* attempt fix

* attempt

* attempt2

* fix

* add to readme

* fix attempt

* another fix attempt

* fix last hopefully

diff --git a/.github/workflows/posemesh-sdk.yml b/.github/workflows/posemesh-sdk.yml
--- a/.github/workflows/posemesh-sdk.yml
+++ b/.github/workflows/posemesh-sdk.yml
@@ -181,6 +181,76 @@ jobs:
           name: Posemesh-Web-SDK-v${{ env.POSEMESH_SDK_VERSION }}.${{ github.run_number }}
           path: ./sdk/out-Web-WASM32-Release/*
 
+  build_linux_sdk:
+    name: Build Linux SDK
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        arch: [AMD64, ARM64]
+
+    steps:
+      - name: Checkout repository with submodules
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Generate interfaces
+        run: |
+          cd sdk/gentool
+          npm run generate
+
+      - name: Install cross-compiler for ARM64
+        if: matrix.arch == 'ARM64'
+        run: |
+          sudo apt-get update
+          sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu clang lld
+
+      - name: Install Rust
+        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+
+      - name: Cache Cargo registry and Git sources (Shared)
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.cargo/registry
+            ~/.cargo/git
+          key: rust-cache-cargo-${{ hashFiles('*/Cargo.lock') }}
+          restore-keys: |
+            rust-cache-cargo-
+
+      - name: Cache Cargo build artifacts (Per Target)
+        uses: actions/cache@v4
+        with:
+          path: ./core/target
+          key: rust-cache-${{ matrix.arch }}-Linux-${{ hashFiles('*/Cargo.lock') }}
+          restore-keys: |
+            rust-cache-${{ matrix.arch }}-Linux-
+
+      - name: Build Posemesh Base
+        shell: pwsh
+        run: ./core/scripts/Build-Library.ps1 Linux ${{ matrix.arch }} Release base -InstallNecessaryRustToolchainsAndTargets
+
+      - name: Build OpenCV
+        shell: pwsh
+        run: ./third-party/scripts/Build-OpenCV-Library.ps1 Linux ${{ matrix.arch }} Release
+
+      - name: Build Posemesh SDK
+        shell: pwsh
+        run: ./sdk/scripts/Build-Library.ps1 Linux ${{ matrix.arch }} Release
+
+      - name: Get Posemesh SDK version
+        run: |
+          POSEMESH_SDK_VERSION=$(pwsh ./sdk/scripts/Get-Version.ps1)
+          if [[ $? -ne 0 ]]; then echo '::error file=sdk/scripts/Get-Version.ps1::Get-Version.ps1 script failed.' 1>&2; exit 1; fi
+          echo "POSEMESH_SDK_VERSION=$POSEMESH_SDK_VERSION" >> $GITHUB_ENV
+
+      - name: Upload Posemesh SDK
+        uses: actions/upload-artifact@v4
+        with:
+          name: Posemesh-Linux-${{ matrix.arch }}-SDK-v${{ env.POSEMESH_SDK_VERSION }}.${{ github.run_number }}
+          path: ./sdk/out-Linux-${{ matrix.arch }}-Release/*
+
   check_code_style:
     name: Check Code Style
     runs-on: ubuntu-latest
